name: buildAllPlatforms

on:
  push:
    branches:  
      - main
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
  workflow_dispatch: {}

#stages:
#  - build
#  - publish

#variables:

jobs:
  buildLinux64:
  #  stage: build
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
#          unityVersion: 2022.3.1f1
#          buildName: anywherelinux64
      - uses: actions/upload-artifact@v2
        with:
          name: StandaloneLinux64
          path: build/StandaloneLinux64
        
